version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    working_dir: /var/www/html
    tty: true
    ports:
      - 8080:80
    links:
      - database
      - maildev
    depends_on:
      - maildev
      - database
    volumes:
      - ./htdocs:/var/www/html

  database:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4
      MYSQL_ROOT_PASSWORD: rootsecret
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - 8000:80
    links:
      - database
  
  maildev:
    image: djfarrelly/maildev
    ports:
      - 8001:80
