#!/bin/sh

set -e

echo "Started entrypoint"

if [ ! -e "/var/www/html/vendor" ]; then
    echo "No vendor folder found, copying from /var/www..."
    cp -R /var/www/vendor /var/www/html/vendor
fi

if [ ! -r "/var/www/html/.env" ]; then
    echo "No .env found, copying from .env.dist..."
    cp /var/www/html/.env.dist /var/www/html/.env
fi

set +e
# create hosts entry for host using host.docker.internal to enable xdebug easily
# in all host environments (Linux, Windows, Mac)
HOST_DOMAIN="host.docker.internal"
ping -q -c1 $HOST_DOMAIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
  HOST_IP=$(ip route|awk '/default/ { print $3 }')
  printf '%s\t%s\n' "$HOST_IP" "$HOST_DOMAIN" >> /etc/hosts
fi
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"

